name: Build asset on macOS

on: [push]

jobs:
  ## ======================================================================================================
  upload_asset_macos_ios_tvos:
    name: Upload asset on macOS (macOS / iOS / tvOS)
    # ref: availabel image - https://github.com/actions/runner-images
    runs-on: macos-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v5

      - name: Install Dependency
        run: brew install coreutils automake

      - name: Run Buildscript
        run: sh ./build-on-mac.sh

      - name: 🎁⏫ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-macos
          path: output
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
