name: Build asset on Windows (x86_64)

on: [push]

jobs:
  build_asset_windows:
    name: Build asset on Windows (x86_64)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install openssl(x86_64)
        run: choco install openssl -y --version "3.2.1" --x86_64

      - name: Prepare build system(MSYS2)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            git
            base-devel
            mingw-w64-x86_64-gcc
            tcl

      - name: Run Buildscript
        shell: msys2 {0}
        run: sh ./build-on-windows-x86_64.sh
